language: objective-c

before_install:
- git submodule --init
- git submodule sync
- git submodule update --recursive
- rvm install 2.2.4
- gem install cocoapods

script:

#build the demo app (Git Submodule)

- xctool -workspace "ShareKit Demo App.xcworkspace" -scheme "ShareKit Demo App" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

#build the demo app (CocoaPods)

- xctool -workspace "ShareKit Demo App.xcworkspace" -scheme "ShareKit Demo App (CocoaPods)" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO